# Generated by Django 4.1.3 on 2022-11-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_sold',
            field=models.IntegerField(default=0),
        ),
    ]
