# Generated by Django 4.1.3 on 2022-11-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='number_of_products',
        ),
        migrations.AddField(
            model_name='order',
            name='total_summa',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
