# Generated by Django 4.1.3 on 2022-11-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_rename_total_order_number_of_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Preaparing', 'Preaparing'), ('OnShipping', 'OnShipping'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='New', max_length=10),
        ),
    ]
