# Generated by Django 4.1.3 on 2022-11-05 18:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_subscribe_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facebook', models.CharField(max_length=40, verbose_name='Facebook')),
                ('twitter', models.CharField(max_length=40, verbose_name='Twitter')),
                ('youtube', models.CharField(max_length=40, verbose_name='Youtube')),
                ('instagram', models.CharField(max_length=40, verbose_name='Instagram')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Logo')),
                ('lat', models.FloatField(verbose_name='Latittude')),
                ('lon', models.FloatField(verbose_name='Longtitude')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.CharField(max_length=20, verbose_name='Email')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('working_days', models.CharField(max_length=100, verbose_name='Working days')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Working hours')),
                ('off_days', models.CharField(max_length=100, verbose_name='Off days')),
                ('off_hours', models.CharField(max_length=100, verbose_name='Off hours')),
                ('about_us', ckeditor.fields.RichTextField(verbose_name='About Us')),
                ('about_us_image', models.ImageField(upload_to='images/', verbose_name='About Us')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
