# Generated by Django 4.1.3 on 2022-11-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='name',
            field=models.CharField(default='Mecina', max_length=40, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
