# Generated by Django 4.1.3 on 2022-11-11 15:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_blog_alter_setting_about_us_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_en',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_ru',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_uz',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject_en',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject_ru',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject_uz',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='about_us_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='About Us'),
        ),
        migrations.AddField(
            model_name='setting',
            name='about_us_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='About Us'),
        ),
        migrations.AddField(
            model_name='setting',
            name='about_us_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='About Us'),
        ),
        migrations.AddField(
            model_name='setting',
            name='name_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='setting',
            name='name_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='setting',
            name='name_uz',
            field=models.CharField(max_length=40, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='setting',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='setting',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='setting',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Title'),
        ),
    ]
