# Generated by Django 4.1.3 on 2022-11-13 09:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_blog_description_en_blog_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='about_us',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About Us'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='about_us_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About Us'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='about_us_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='About Us Image'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='about_us_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About Us'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='about_us_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About Us'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='facebook',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='instagram',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name_en',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name_ru',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name_uz',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='off_days',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Off days'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='off_hours',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Off hours'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title_uz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='twitter',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='working_days',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Working days'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='working_hours',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Working hours'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='youtube',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Youtube'),
        ),
    ]
